### ISSUE TITLE
Fix and upload jgraphx-jre8 to AUR

### ISSUE THREAD

**Issue by petronny** [GoliathLabs/aurpackages#2]
Please add `provides` and `conflicts` to PKGBUILD.
And update its `depends` to something like `('java-runtime=8')`.

Then please upload  it to AUR and specific it as a dependency of `scilab`.

**Comment by petronny** [comment]
Hi, could you fix this issue?

Once it's fixed, my build system can provide pre-built arch packages which can benefits all scilab users.

**Comment by GoliathLabs** [comment]
Updated both in the AUR :) Feel free to try things out :)
