### ISSUE TITLE
apache-lucene package outdated

### ISSUE THREAD

**Issue by vccolombo** [GoliathLabs/aurpackages#4]
Apparently https://downloads.apache.org/lucene/java/ has been updated to 8.6.2 and the 8.6.1 version is now returning 404 when trying to download:

```terminal
$ pamac build scilab

...
...

curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://downloads.apache.org/lucene/java/8.6.1/lucene-8.6.1.tgz
    Aborting...
Error: Failed to build apache-lucene
```
Which aborts scilab installation

**Comment by GoliathLabs** [comment]
Updated the apache-lucene package :)On Sep 1, 2020 8:08 PM, Víctor Colombo <notifications@github.com> wrote:
Apparently https://downloads.apache.org/lucene/java/ has been updated to 8.6.2 and the 8.6.1 version is now returning 404 when trying to download:
$ pamac build scilab

...
...

curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading https://downloads.apache.org/lucene/java/8.6.1/lucene-8.6.1.tgz
    Aborting...
Error: Failed to build apache-lucene

Which aborts scilab installation
